-- Display-friendly columns for Supabase Table Editor / exports:
-- serial_no: 1, 2, 3… per insert order (by punch time)
-- employee_name: denormalized from employees.full_name (kept in sync via trigger)

ALTER TABLE public.attendance_punches
  ADD COLUMN IF NOT EXISTS serial_no bigint,
  ADD COLUMN IF NOT EXISTS employee_name text;

-- Backfill serial numbers in chronological order
WITH numbered AS (
  SELECT id, row_number() OVER (ORDER BY punch_at, created_at, id) AS rn
  FROM public.attendance_punches
)
UPDATE public.attendance_punches p
SET serial_no = n.rn
FROM numbered n
WHERE p.id = n.id
  AND p.serial_no IS NULL;

-- Backfill employee names
UPDATE public.attendance_punches p
SET employee_name = e.full_name
FROM public.employees e
WHERE e.id = p.employee_id
  AND (p.employee_name IS NULL OR p.employee_name = '');

ALTER TABLE public.attendance_punches
  ALTER COLUMN serial_no SET NOT NULL;

-- Identity for new rows (continues after backfill max)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'attendance_punches'
      AND a.attname = 'serial_no'
      AND a.attidentity <> ''
  ) THEN
    ALTER TABLE public.attendance_punches
      ALTER COLUMN serial_no ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

SELECT setval(
  pg_get_serial_sequence('public.attendance_punches', 'serial_no'),
  COALESCE((SELECT MAX(serial_no) FROM public.attendance_punches), 0) + 1,
  false
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_attendance_punches_serial_no
  ON public.attendance_punches (serial_no);

CREATE OR REPLACE FUNCTION public.attendance_punches_set_employee_name()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  SELECT e.full_name INTO NEW.employee_name
  FROM public.employees e
  WHERE e.id = NEW.employee_id;

  IF NEW.employee_name IS NULL THEN
    RAISE EXCEPTION 'Employee % not found for attendance punch', NEW.employee_id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_attendance_punches_employee_name ON public.attendance_punches;
CREATE TRIGGER trg_attendance_punches_employee_name
  BEFORE INSERT OR UPDATE OF employee_id ON public.attendance_punches
  FOR EACH ROW
  EXECUTE FUNCTION public.attendance_punches_set_employee_name();

-- Keep employee_name current when an employee is renamed
CREATE OR REPLACE FUNCTION public.employees_sync_punch_names()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.full_name IS DISTINCT FROM OLD.full_name THEN
    UPDATE public.attendance_punches
    SET employee_name = NEW.full_name
    WHERE employee_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_employees_sync_punch_names ON public.employees;
CREATE TRIGGER trg_employees_sync_punch_names
  AFTER UPDATE OF full_name ON public.employees
  FOR EACH ROW
  EXECUTE FUNCTION public.employees_sync_punch_names();

COMMENT ON COLUMN public.attendance_punches.serial_no IS 'Display row number (1, 2, 3…) assigned on insert.';
COMMENT ON COLUMN public.attendance_punches.employee_name IS 'Employee full name at punch time; synced from employees.full_name.';
